### ISSUE TITLE
New municipalities as of January 2019 need to be updated/added

### ISSUE THREAD

**Issue by Korneelmans** [Datafable/rolling-blackout-belgium#55]
1. Since January 2019, 7 new municipalities were created, replacing 15 existing ones. Their territories are simple unions of previously existing municipalities. The details are here : https://overheid.vlaanderen.be/informatie-vlaanderen/gemeentelijke-fusies

2. Can you make sure the database update gets pushed to https://www.tableaumapping.bi ?

Thanks!

**Comment by bartaelterman** [comment]
Hi @Korneelmans 
The last changes to this repository are from 5 years ago and we lack resources to keep actively maintaining it.
However, as we explained in [this README](https://github.com/Datafable/rolling-blackout-belgium/tree/master/data/geospatial) we got the municipalities geojson file from another source. It could be worth checking whether the original publisher has made the changes you are looking for.
If not, please note that the [LICENCE file](https://github.com/Datafable/rolling-blackout-belgium/blob/master/LICENSE) we added to this repository is very permissive. So feel free to use [the geojson file we shared](https://github.com/Datafable/rolling-blackout-belgium/blob/master/data/geospatial/municipalities-belgium.geojson) and adapt it to your needs.

**Comment by lgeorget** [comment]
Hi !
Just chiming in to let you know that there are now great resources available freely on https://www.geo.be and https://data.gov.be/.

This dataset in particular https://www.geo.be/catalog/details/fb1e2993-2020-428c-9188-eb5f75e284b9?l=fr (or equivalently https://data.gov.be/fr/dataset/fb1e2993-2020-428c-9188-eb5f75e284b9) contains administrative boundaries for several levels (as well as other economic sectors boundaries, etc.).
